/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author pasca
 */
public class Etudiant extends javax.swing.JFrame {

    /**
     * Creates new form Etudiant
     */
    public Etudiant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jSpinField1 = new com.toedter.components.JSpinField();
        retouretudiant = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        gererselection = new javax.swing.JButton();
        nom = new javax.swing.JTextField();
        nationalite = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Etudiant");
        setBackground(new java.awt.Color(255, 51, 255));
        setName("frmetudiant"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                FermerEtudiant(evt);
            }
        });

        retouretudiant.setText("Quitter");
        retouretudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourEtudiant(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(table);

        jButton1.setText("Rechercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        gererselection.setText("Supprimer");
        gererselection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gererselectionActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom");

        jLabel2.setText("Nationalité");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1157, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(retouretudiant))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(52, 52, 52)
                                .addComponent(gererselection))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nom)
                                    .addComponent(nationalite, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(retouretudiant)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nationalite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(gererselection))))
                .addContainerGap(379, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void FermerEtudiant(java.awt.event.WindowEvent evt) {                                
        // TODO add your handling code here:
        Menud md = new Menud();
        this.hide();
        //md.setVisible(true);
        md.show();
    }                               

    private void RetourEtudiant(java.awt.event.ActionEvent evt) {                                
        // TODO add your handling code here:
        Menud md = new Menud();
        this.hide();
        md.setVisible(true);
        //md.show();
    }                               

 //public static TableModel resultSetToTableModel(ResultSet res) {
 public TableModel resultSetToTableModel(ResultSet res) 
 {
  try {
        ResultSetMetaData metaData = res.getMetaData();
        int nbcols = metaData.getColumnCount();
        Vector nomCols = new Vector();
        // Noms des colonnes (Titres)
        for (int column = 0; column < nbcols; column++) 
        {
           nomCols.addElement(metaData.getColumnLabel(column + 1));
        }
        // Les lignes de données.
         Vector lignes = new Vector();
         while (res.next()) 
         {
             Vector newLigne = new Vector();
             for (int i = 1; i <= nbcols; i++) 
             {
                newLigne.addElement(res.getObject(i));
             }
             lignes.addElement(newLigne);
         }
         return new DefaultTableModel(lignes, nomCols);
      } 
      catch (Exception e) 
      {
        e.printStackTrace();
        return null;
      }
   }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        //
        ResultSet rs=null;
        Statement stm=null;
        Connection con=null;
        //
        String noms = nom.getText();
        String nat = nationalite.getText();
        //
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");

        }
        catch(ClassNotFoundException e)
        {
            System.out.println(e.getMessage());
        }
        //
        String url = "jdbc:mysql://localhost:3306/gsao?serverTimezone=UTC";
        String user = "root";
        String pswd = "";
        //
        try{
            con = DriverManager.getConnection(url,user,pswd);
            //
        }
        catch(SQLException e)
        {
            System.out.println(e.getMessage());
        }

        //
        String rqt = "select id,nom,prenom,nationalite,cin,email from etudiant where nom like '"+noms+"%' and nationalite like '"+nat+"%';";
        try{
            stm = con.createStatement() ;
            //
            rs = stm.executeQuery(rqt);
            //
            //      
            table.setModel(resultSetToTableModel(rs));
            //            
            //
        }
        catch(NullPointerException e)
        {
            System.out.println(e.getMessage());
        }
        catch(SQLException e)
        {
            System.out.println(e.getMessage());
        }

    }                                        

    private void gererselectionActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        String msg = "Sélection en cours de traitement!";
        int numligne = table.getSelectedRow();
        int numcol = table.getSelectedColumn();
        //int intrvLig = table.getSelectedRowCount();
        //
        String codsel = table.getValueAt(numligne, 0).toString();
        String nomsel = table.getValueAt(numligne, 1).toString();
        String prensel = table.getValueAt(numligne, 2).toString();
        //
        //String mess = "Ligne sélectionnée : " + numligne;
        //String mess2 = "Lignes sélectionnées : " + intrvLig;
        //String mess3 = "Nom Etudiant sélectionné : " + codsel + " ** Nom / Prénom : " + nomsel + " " + prensel;
        //
        //javax.swing.JOptionPane.showMessageDialog(rootPane, mess3);
         ResultSet rs=null;
        Statement stm=null;
        Connection con=null;
        //
         //
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");

        }
        catch(ClassNotFoundException e)
        {
            System.out.println(e.getMessage());
        }
        //
        String url = "jdbc:mysql://localhost:3306/gsao?serverTimezone=UTC";
        String user = "root";
        String pswd = "";
        //
        try{
            con = DriverManager.getConnection(url,user,pswd);
            //
        }
        catch(SQLException e)
        {
            System.out.println(e.getMessage());
        }

        //
        String rqt = "delete from etudiant where id="+codsel; //"select id,nom,prenom,nationalite,cin,email from etudiant where nom like '"+noms+"%';";
        try{
            stm = con.createStatement() ;
            //
           // rs = stm.executeQuery(rqt);
            //
            stm.executeUpdate(rqt);
            //      
            //table.setModel(resultSetToTableModel(rs));
            //            
            //
        }
        catch(NullPointerException e)
        {
            System.out.println(e.getMessage());
        }
        catch(SQLException e)
        {
            System.out.println(e.getMessage());
        }
        
        
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Etudiant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton gererselection;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.components.JSpinField jSpinField1;
    private javax.swing.JTextField nationalite;
    private javax.swing.JTextField nom;
    private javax.swing.JButton retouretudiant;
    private javax.swing.JTable table;
    // End of variables declaration                   
}
